name: Deploy Site

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy over SSH
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
        command: cd dota2stats.io && git checkout master && git pull && docker-compose up --build -d