name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          cd dota2stats.io
          git checkout master
          git pull
          docker-compose up --build -d