name: Deploy Site

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Write SSH key
      run: |
        echo making directory
        mkdir ~/.ssh
        echo writing private key
        echo "$REMOTE_SSH_KEY" > $HOME/.ssh/gh_actions_key
        echo changing key permissions 
        chmod 600 $HOME/.ssh/gh_actions_key
        echo listing directory contents
        ls -la $HOME/.ssh

    - name: Deploy over SSH
      run: |
        echo starting ssh
        echo $REMOTE_USER
        echo $REMOTE_HOST
        echo ssh -i $HOME/.ssh/gh_actions_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$REMOTE_USER"@"$REMOTE_HOST" "cd dota2stats.io && git checkout master && git pull && docker-compose up --build -d"
        ssh -i $HOME/.ssh/gh_actions_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "$REMOTE_USER"@"$REMOTE_HOST" "cd dota2stats.io && git checkout master && git pull && docker-compose up --build -d"