name: Deploy Site

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy over SSH
      uses: actions/checkout@v2
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
        REMOTE_SSH_KEY: ${{ secrets.REMOTE_SSH_KEY }}
        REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      run: |
        mkdir ~/.ssh
        echo "$REMOTE_SSH_KEY" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key
        ssh -i ~/.ssh/gh_action_key "$REMOTE_USERNAME"@"$REMOTE_HOST" "cd dota2stats.io && git checkout master && git pull && docker-compose up --build -d"